spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: abcd1234.

  sql:
    init:
      mode: always
      
  flyway:
    baseline-on-migrate: true 